name: kinetic
version: 1.0.0-rc.1+1
description: The official Kinetic Dart SDK brought to you by the Kin Foundation.
homepage: https://github.com/kin-labs/kinetic-dart
repository: https://github.com/kin-labs/kinetic-dart
issue_tracker: https://github.com/kin-labs/kinetic-dart/issues
documentation: https://kinetic.kin.org/docs/sdk/dart

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.6
  bs58: ^1.0.2
  http: ^0.13.5
  intl: ^0.17.0
  logger: ^1.1.0
  meta: ^1.8.0
  solana: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

