name: flutter-test

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  main:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: prisma
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      solana:
        image: ghcr.io/kin-labs/kinetic-solana-network:latest
        ports: [ '8899:8899', '8900:8900' ]
      kinetic:
        image: ghcr.io/kin-labs/kinetic:1.0.0-rc.7
        ports:
          - 3000:3000
        env:
          API_URL: 'http://localhost:3000'
          APP_1_FEE_PAYER_BYTE_ARRAY: '[24,20,238,188,26,234,120,209,88,63,170,46,66,98,21,113,194,120,143,228,231,37,91,0,242,32,180,99,243,179,57,144,11,233,235,235,203,20,105,33,47,140,152,253,12,148,72,175,141,253,242,110,225,110,21,211,118,87,111,206,208,166,190,78]'
          APP_1_NAME: 'App 1'
          AUTH_USERS: 'alice|Kinetic@alice1|Admin,bob|Kinetic@bob1'
          AUTH_PASSWORD_ENABLED: true
          COOKIE_DOMAINS: 'localhost'
          COOKIE_NAME: '__session'
          CORS_ORIGINS: '*'
          DATABASE_URL: 'postgresql://prisma:prisma@postgres:5432/prisma?schema=kinetic'
          HOST: '0.0.0.0'
          JWT_SECRET: 'KineticJwtSecret!'
          NX_CLOUD_DISTRIBUTED_EXECUTION: false
          SOLANA_LOCAL_ENABLED: true
          SOLANA_LOCAL_MINT_KIN: '*MoGaMuJnB3k8zXjBYBnHxHG47vWcW3nyb7bFYvdVzek,5,Kin'
          SOLANA_LOCAL_MINT_KIN_AIRDROP_SECRET_KEY: '[24,20,238,188,26,234,120,209,88,63,170,46,66,98,21,113,194,120,143,228,231,37,91,0,242,32,180,99,243,179,57,144,11,233,235,235,203,20,105,33,47,140,152,253,12,148,72,175,141,253,242,110,225,110,21,211,118,87,111,206,208,166,190,78]'
          SOLANA_LOCAL_MINT_USDC: '*USDzo281m7rjzeZyxevkzL1vr5Cibb9ek3ynyAjXjUM,2,USDC'
          SOLANA_LOCAL_MINT_USDC_AIRDROP_SECRET_KEY: '[24,20,238,188,26,234,120,209,88,63,170,46,66,98,21,113,194,120,143,228,231,37,91,0,242,32,180,99,243,179,57,144,11,233,235,235,203,20,105,33,47,140,152,253,12,148,72,175,141,253,242,110,225,110,21,211,118,87,111,206,208,166,190,78]'
          SOLANA_LOCAL_RPC_ENDPOINT: 'http://solana:8899'
          WEB_URL: 'http://localhost:3000'
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter test
